#!/usr/bin/env ksh
# Performs tests on agrepy via the python program testagrepy.py

# args are: <indel count [-e]> <pattern string> <infile name> <outfile name>
function run_a_test {
  testagrepy.py -$1 -s $2 $3 > out
  if cmp out $4
  then
    echo "Test: $1 $2 $3 ok"
  else
    echo "Test: $1 $2 $3 fails"
  fi
}

function run_an_errs_test {
  testagrepy.py -$1 -s $2 $3 > out 2> errs
  if cmp out $4
  then
    if cmp errs $5
    then
	echo "Test: $1 $2 $3 ok"
    else
        echo "Test: $1 $2 $3 fails (output ok; errors incorrect)"
    fi
 else
    echo "Test: $1 $2 $3 fails"
 fi
}


SHORT_LONG=$(awk '$2=="SHORT_LONG" {print $3}' agrepy.h)
sed -e "/SHORT_LONG/s/$SHORT_LONG/100/" agrepy.h > xxx
mv xxx agrepy.h

print "\nTesting sagrepy (short-string matching)\n"

make clean
make
print
I=1
for S in Actinomycetaceae caggcctaacacatgcaagtc caggcctaacacatgcaagtc
do
  run_a_test 3 $S xxxy$I out$I
  I=$(($I + 1))
done

sed -e "/SHORT_LONG/s/100/1/" agrepy.h > xxx
mv xxx agrepy.h

print "\nTesting lagrepy (long-string matching)\n"

make clean
make
echo
I=1
for S in Actinomycetaceae caggcctaacacatgcaagtc caggcctaacacatgcaagtc
do
  run_a_test 3 $S xxxy$I out$I
  I=$(($I + 1))
done

print "\nTesting extension of matching to cover entire pattern\n"

run_a_test "3 -e" Actinomycetaceae xxxy1 out1e
run_a_test "3 -e" caggcctaacacatgcaagtc xxxy3 out3e

print "\nVery long text string"
run_a_test 1 PQIAMFCGRLNMHMNVQNGKW long_string out.long

print "\nSome error conditions"

run_an_errs_test 0 Actinomycetaceae xxxy1 out.errs1 errs.errs1
run_an_errs_test 1 $(<long_pattern) long_string out.errs2  errs.errs2


# Tidy up!
sed -e "/SHORT_LONG/s/1/$SHORT_LONG/" agrepy.h > xxx
mv xxx agrepy.h
rm out
